spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:db/MedicalGame-sqlite3.db
    username:
    password:

mybatis:
  type-aliases-package: org.northwest.newserver.pojo
server:
  port: 8081
#  servlet:
#    context-path: "/MedicalGame"
